all:
  hosts:
    10.130.10.10:
  children:      
    repo_server:
      hosts:
        10.130.5.11:       
    k8s_server:
      hosts:
        10.130.10.11:
        10.130.100.70:
      vars:
        ansible_user: root
        ansible_password: 123456a@